### ISSUE TITLE
Cannot read properties of undefined (reading 'locale')

### ISSUE THREAD

**Issue by tnagels** [pkissling/clock-weather-card#44]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**

..**Last working release (if known):**
1.0.4
**Browser and Operating System:**
iOS HA App / Windows Edge 

**Description of problem:**

Just added the card, it just shows an error. On the browser I get "Cannot read properties of undefined (reading 'locale')", in the HA app it shows "undefined is not an object (evaluating 'this.config.locale')". The same message is shown in the console.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by pkissling** [comment]
hi @tnagels, thanks for reporting the issue. could you please provide the stacktrace?

**Comment by tnagels** [comment]
Do you mean this?

`ha-logbook.ts:42 
        
       card custom:clock-weather-card TypeError: Cannot read properties of undefined (reading 'locale')
    at lt.getLocale (clock-weather-card.js?hacstag=522634019104:231:1984)
    at lt.localize (clock-weather-card.js?hacstag=522634019104:231:3436)
    at lt.setConfig (clock-weather-card.js?hacstag=522634019104:171:211019)
    at a (ha-logbook.ts:42:1)
    at ha-logbook.ts:42:1
    at u (ha-logbook.ts:42:1)
    at d (ha-logbook.ts:42:1)
    at v (ha-logbook.ts:42:1)
    at r.value (hui-masonry-view.ts:44:1)
    at hui-masonry-view.ts:44:1`

**Comment by tnagels** [comment]
Just updatedc to 1.0.5 and now I get a different error:
```
card custom:clock-weather-card Error
    at Bt.setConfig (clock-weather-card.js?hacstag=522634019105:171:214244)
    at a (ha-logbook.ts:42:1)
    at ha-logbook.ts:42:1
    at u (ha-logbook.ts:42:1)
    at d (ha-logbook.ts:42:1)
    at v (ha-logbook.ts:42:1)
    at r.value (cec1ec6d.js:1:9934)
    at r.value (cec1ec6d.js:1:9459)
    at r.performUpdate (styles.ts:370:1)
    at r.scheduleUpdate (styles.ts:370:1)
```

**Comment by pkissling** [comment]
thanks. can you also provide your `yaml` configuration (dashboard)?

**Comment by pkissling** [comment]
hi @tnagels 
i just found out that the error message was missing a translation. the error message which was supposed to show is: "entity must be present". this will be fixed in the next release.

the error message says that you did not provide the `entity` attribute in the configuration.

a sample configuration:
```
- type: custom:clock-weather-card
  entity: weather.home
```

can you check whether this resolves your issue?

**Comment by tnagels** [comment]
@pkissling yes, that did solve the issue. In the end it was my fault for not adding the entity, but I'm glad you found the translation error.
