### ISSUE TITLE
Daily lines are overlapping

### ISSUE THREAD

**Issue by ofirmanor** [pkissling/clock-weather-card#477]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser
- [ X I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
2.8.5
**Last working release (if known):**
Just downloaded clock-weather-card today using HACS
**Browser and Operating System:**
Latest Microsoft Edge (Version 130.0.2849.68 (Official build) (64-bit)) on Windows 11

I just starting using it and loving it!
However, using daily forecast, two days are a bit overlapping (Thu+Fri in the screenshot)
![image](https://github.com/user-attachments/assets/cd9958ce-8de5-4bc5-9d40-b88a3e3188ed)

Tried to use multiple variations of the config (removing bits etc), nothing helped.
This is the config for this screenshot

type: custom:clock-weather-card
entity: weather.ims_weather
forecast_rows: 6
title: Raanana Forecast
weather_icon_type: fill
show_humidity: false
time_pattern: H:mm
date_pattern: cccc, LLL M 

All daily lines should be have same spacing, and not overlapping?

**Javascript errors shown in the web inspector (if applicable):**
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "action-handler-clock-weather" has already been used with this registry
    at window.CustomElementRegistry.define (http://ha-guest:8123/frontend_latest/app.8g4YhNxag-w.js:2:4271)
    at http://ha-guest:8123/hacsfiles/clock-weather-card/clock-weather-card.js:180:2352

scoped-custom-element-registry.js:1 
        Failed to load resource: the server responded with a status of 404 (Not Found)

**Additional information:**

**Comment by ofirmanor** [comment]
Oh, checked the Android app, same exact issue

**Comment by pkissling** [comment]
hi @ofirmanor,

thanks for reporting the issue. the fact that there is no icon for Thu and Fri makes me believe that your weather service might report a weather state, which is not mapped in `clock-weather-card`. can you provide the weather state for those two days?
a list of all the expected and mapped states can be found here: https://github.com/pkissling/clock-weather-card/blob/master/src/images.ts#L87

**Comment by ofirmanor** [comment]
Thanks for the fast reply @pkissling !
The weather service is ims-custom-component from HACS https://github.com/GuyKh/ims-custom-component
Today I see that Friday doesn't have an icon
![image](https://github.com/user-attachments/assets/e1ed71e9-779f-4caa-9c49-c66a8d0dd00f)

If I got it right, the status of the day is Dust
<img width="501" alt="image" src="https://github.com/user-attachments/assets/7e77e21a-3395-41e0-8445-e6bcfa3f38de">

Which I don't see in the list of icons.
Are you saying that is likely the cause of the visual issue? Can it be mapped to the closest possible icon or something?

**Comment by ofirmanor** [comment]
Oh, alternatively - if a weather status is unknown, maybe have an empty / question mark icon, so there will be something with the right number of pixels? so the display won't be messed up?

**Comment by ofirmanor** [comment]
Just wanted to update that this is definitely the missing icon!
The forecast has updated, now all the days have icons and it looks perfect
<img width="386" alt="image" src="https://github.com/user-attachments/assets/57705b6f-61d6-4c3c-ae65-55b8abd56c79">
Hoping you can implement one of the workarounds

**Comment by pkissling** [comment]
hi,
according to the official home assistant weather documentation `dust` is not a valid status.

https://www.home-assistant.io/integrations/weather/#condition-mapping

if the weather is really dusty and not foggy, the weather provider should map the state to `exceptional`

**Comment by ofirmanor** [comment]
@pkissling ok got it, makes sense
I'll take it to the weather service github and see if I can interest them in finding a solution.
Would you consider adding an empty, transparent image to handle this edge case in your component? That would be super. 
If not you could close this ticket...  thanks!

**Comment by pkissling** [comment]
yeah, makes sense. i'll use this ticket to fix the margin for cases where the icon is missing
